#### DATASET
#### Dataset contains information about flight booking options from the website Easemytrip for flight travel between India's top 6 metro cities. There are #### 300261 datapoints and 11 features in the cleaned dataset.
#### 
#### FEATURES
#### The various features of the cleaned dataset are explained below: 
#### 1) Airline: The name of the airline company is stored in the airline column. It is a categorical feature having 6 different airlines. 
#### 
#### 2) Flight: Flight stores information regarding the plane's flight code. It is a categorical feature. 
#### 
#### 3) Source City: City from which the flight takes off. It is a categorical feature having 6 unique cities. 
#### 
#### 4) Departure Time: This is a derived categorical feature obtained created by grouping time periods into bins. It stores information about the departure #### time and have 6 unique time labels. 
#### 
#### 5) Stops: A categorical feature with 3 distinct values that stores the number of stops between the source and destination cities. 
#### 
#### 6) Arrival Time: This is a derived categorical feature created by grouping time intervals into bins. It has six distinct time labels and keeps inf orm#ation ###about the arrival time. 
#### 
#### 7) Destination City: City where the flight will land. It is a categorical feature having 6 unique cities. 
#### 
#### 8) Class: A categorical feature that contains information on seat class; it has two distinct values: Business and Economy. 
#### 
#### 9) Duration: A continuous feature that displays the overall amount of time it takes to travel between cities in hours. 
#### 
#### 10)Days Left: This is a derived characteristic that is calculated by subtracting the trip date by the booking date. 
#### 
#### 11) Price: Target variable stores information of the ticket price.

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [50]:
df = pd.read_excel('flight_price.xlsx')

In [51]:
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [52]:
#basic info about the data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [53]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [54]:
## feacture engineering
df['Date']=df['Date_of_Journey'].str.split('/').str[0]

In [55]:
df.Date

0        24
1         1
2         9
3        12
4        01
         ..
10678     9
10679    27
10680    27
10681    01
10682     9
Name: Date, Length: 10683, dtype: object

In [56]:
df['Month'] = df['Date_of_Journey'].str.split('/').str[1]
df['Year'] = df['Date_of_Journey'].str.split('/').str[2]

In [57]:
df[['Date', 'Month', 'Year']]

      Date Month  Year
0       24    03  2019
1        1    05  2019
2        9    06  2019
3       12    05  2019
4       01    03  2019
...    ...   ...   ...
10678    9    04  2019
10679   27    04  2019
10680   27    04  2019
10681   01    03  2019
10682    9    05  2019

[10683 rows x 3 columns]

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  object
 12  Month            10683 non-null  object
 13  Year             10683 non-null  object
dtypes: int64(1), object(3), str(10)
memory usage: 1.1+ MB

In [59]:
df['Date']= df['Date'].astype('Int64')
df['Month']=df['Month'].astype('Int64')
df['Year']=df['Year'].astype('Int64')

In [60]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
 11  Date             10683 non-null  Int64
 12  Month            10683 non-null  Int64
 13  Year             10683 non-null  Int64
dtypes: Int64(3), int64(1), str(10)
memory usage: 1.2 MB

In [61]:
df.drop('Date_of_Journey', axis= 1, inplace= True)

In [62]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019

In [63]:
df.tail()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107,9,4,2019
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145,27,4,2019
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229,27,4,2019
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648,1,3,2019
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753,9,5,2019

In [64]:
df.Dep_Time.unique()

<StringArray>
['22:20', '05:50', '09:25', '18:05', '16:50', '09:00', '18:55', '08:00',
 '08:55', '11:25',
 ...
 '15:35', '13:40', '07:20', '04:50', '12:45', '10:25', '12:05', '11:20',
 '21:40', '03:00']
Length: 222, dtype: str

In [65]:
df['Arrival_Time'] = df['Arrival_Time'].apply(lambda x: x.split(' ')[0])

In [66]:
df["Arrival_hour"]= df['Arrival_Time'].str.split(':').str[0]
df["Arrival_min"]= df['Arrival_Time'].str.split(':').str[1]

In [67]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [68]:
df.drop("Arrival_Time", axis=1,inplace=True)

In [69]:
df['Dep_hour']=df['Dep_Time'].str.split(':').str[0]
df['Dep_min']=df['Dep_Time'].str.split(':').str[1]

In [70]:
df.tail()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
10678,Air Asia,Kolkata,Banglore,CCU → BLR,19:55,2h 30m,non-stop,No info,4107,9,4,2019,22,25,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,20:45,2h 35m,non-stop,No info,4145,27,4,2019,23,20,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,08:20,3h,non-stop,No info,7229,27,4,2019,11,20,08,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,11:30,2h 40m,non-stop,No info,12648,1,3,2019,14,10,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,8h 20m,2 stops,No info,11753,9,5,2019,19,15,10,55

In [71]:
df.drop("Dep_Time", axis=1,inplace=True)

In [72]:
df["Arrival_hour"] = df["Arrival_hour"].astype("Int64")
df["Arrival_min"] = df["Arrival_min"].astype("Int64")
df["Dep_min"] = df["Dep_min"].astype("Int64")
df["Dep_hour"] = df["Dep_hour"].astype("Int64")

In [73]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Duration         10683 non-null  str
 5   Total_Stops      10682 non-null  str
 6   Additional_Info  10683 non-null  str
 7   Price            10683 non-null  int64
 8   Date             10683 non-null  Int64
 9   Month            10683 non-null  Int64
 10  Year             10683 non-null  Int64
 11  Arrival_hour     10683 non-null  Int64
 12  Arrival_min      10683 non-null  Int64
 13  Dep_hour         10683 non-null  Int64
 14  Dep_min          10683 non-null  Int64
dtypes: Int64(7), int64(1), str(7)
memory usage: 1.3 MB

In [74]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [75]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [76]:
df[df['Total_Stops'].isnull()]

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
9039,Air India,Delhi,Cochin,NaN,23h 40m,NaN,No info,7480,6,5,2019,9,25,9,45

In [77]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: str

In [78]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [79]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop':0, '2 stops':2, '1 stop' : 1, '3 stops':3, np.nan : 1, '4 stops':4})

In [80]:
df

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1,No info,13302,1,3,2019,21,35,16,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,CCU → BLR,2h 30m,0,No info,4107,9,4,2019,22,25,19,55
10679,Air India,Kolkata,Banglore,CCU → BLR,2h 35m,0,No info,4145,27,4,2019,23,20,20,45
10680,Jet Airways,Banglore,Delhi,BLR → DEL,3h,0,No info,7229,27,4,2019,11,20,8,20
10681,Vistara,Banglore,New Delhi,BLR → DEL,2h 40m,0,No info,12648,1,3,2019,14,10,11,30
10682,Air India,Delhi,Cochin,DEL → GOI → BOM → COK,8h 20m,2,No info,11753,9,5,2019,19,15,10,55

In [81]:
df['Destination'].unique()

<StringArray>
['New Delhi', 'Banglore', 'Cochin', 'Kolkata', 'Delhi', 'Hyderabad']
Length: 6, dtype: str

In [82]:
df['Duration_hour'] = (
    df['Duration']
    .str.extract(r'(\d+)h')
    .fillna(0)
)

df['Duration_min'] = (
    df['Duration']
    .str.extract(r'(\d+)m')
    .fillna(0)
)

In [83]:
df['Duration_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', 0, '41', '40'], dtype=object)

In [84]:
df['Duration_min'].unique()

array(['50', '25', 0, '45', '30', '5', '15', '35', '10', '20', '55', '40'],
      dtype=object)

In [85]:
df['Duration_hour']=df['Duration_hour'].astype('Int64')
df['Duration_min']=df['Duration_min'].astype('Int64')

TypeError: cannot safely cast non-equivalent object to int64

In [ ]:
df.head(2)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Duration_hour,Duration_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,2019,1,10,22,20,2,50
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2,No info,7662,1,5,2019,13,15,5,50,7,25

In [ ]:
df["Airline"].unique()

<StringArray>
[                           'IndiGo',                         'Air India',
                       'Jet Airways',                          'SpiceJet',
                 'Multiple carriers',                             'GoAir',
                           'Vistara',                          'Air Asia',
           'Vistara Premium economy',              'Jet Airways Business',
 'Multiple carriers Premium economy',                            'Trujet']
Length: 12, dtype: str

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()

In [ ]:
encoded = encoder.fit_transform(df[["Airline", "Source" , 'Destination']]).toarray()

In [ ]:
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())

In [ ]:
df = pd.concat([df, encoded_df],axis=1)

In [ ]:
df.head(1)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,0,No info,3897,24,3,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df.drop(['Airline','Destination','Source', 'Route','Duration'], axis=1, inplace=True)

In [ ]:
df.head(1)

,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0,No info,3897,24,3,2019,1,10,22,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 35 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Stops                                10683 non-null  int64
 1   Additional_Info                            10683 non-null  str
 2   Price                                      10683 non-null  int64
 3   Date                                       10683 non-null  Int64
 4   Month                                      10683 non-null  Int64
 5   Year                                       10683 non-null  Int64
 6   Arrival_hour                               10683 non-null  Int64
 7   Arrival_min                                10683 non-null  Int64
 8   Dep_hour                                   10683 non-null  Int64
 9   Dep_min                                    10683 non-null  Int64
 10  Duration_hour                              10683 non-null  object
 11  Duration_min                               10683 non-null  object
 12  Airline_Air Asia                           10683 non-null  float64
 13  Airline_Air India                          10683 non-null  float64
 14  Airline_GoAir                              10683 non-null  float64
 15  Airline_IndiGo                             10683 non-null  float64
 16  Airline_Jet Airways                        10683 non-null  float64
 17  Airline_Jet Airways Business               10683 non-null  float64
 18  Airline_Multiple carriers                  10683 non-null  float64
 19  Airline_Multiple carriers Premium economy  10683 non-null  float64
 20  Airline_SpiceJet                           10683 non-null  float64
 21  Airline_Trujet                             10683 non-null  float64
 22  Airline_Vistara                            10683 non-null  float64
 23  Airline_Vistara Premium economy            10683 non-null  float64
 24  Source_Banglore                            10683 non-null  float64
 25  Source_Chennai                             10683 non-null  float64
 26  Source_Delhi                               10683 non-null  float64
 27  Source_Kolkata                             10683 non-null  float64
 28  Source_Mumbai                              10683 non-null  float64
 29  Destination_Banglore                       10683 non-null  float64
 30  Destination_Cochin                         10683 non-null  float64
 31  Destination_Delhi                          10683 non-null  float64
 32  Destination_Hyderabad                      10683 non-null  float64
 33  Destination_Kolkata                        10683 non-null  float64
 34  Destination_New Delhi                      10683 non-null  float64
dtypes: Int64(7), float64(23), int64(2), object(2), str(1)
memory usage: 2.9+ MB

In [ ]:
df.describe()

,Total_Stops,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dep_hour,Dep_min,Airline_Air Asia,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
count,10683.000000,10683.000000,10683.0,10683.0,10683.0,10683.0,10683.0,10683.0,10683.0,10683.000000,...,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000,10683.000000
mean,0.824207,9087.064121,13.508378,4.708602,2019.0,13.348778,24.69063,12.490686,24.411214,0.029861,...,0.035664,0.424693,0.268745,0.065244,0.268745,0.424693,0.118412,0.065244,0.035664,0.087241
std,0.675199,4611.359167,8.479277,1.164357,0.0,6.859125,16.506036,5.74865,18.76798,0.170210,...,0.185460,0.494320,0.443328,0.246967,0.443328,0.494320,0.323111,0.246967,0.185460,0.282202
min,0.000000,1759.000000,1.0,3.0,2019.0,0.0,0.0,0.0,0.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,5277.000000,6.0,3.0,2019.0,8.0,10.0,8.0,5.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,8372.000000,12.0,5.0,2019.0,14.0,25.0,11.0,25.0,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,12373.000000,21.0,6.0,2019.0,19.0,35.0,18.0,40.0,0.000000,...,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,4.000000,79512.000000,27.0,6.0,2019.0,23.0,55.0,23.0,55.0,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000